[package]
name = "pennykite-providers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pennykite-types = { path = "../pennykite-types" }
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde_yaml.workspace = true
